web:
  restart: always
  build: ../
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/peri2organise/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 peri2organise:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

data:
  restart: "no"
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  environment:
    POSTGRES_USER: "peri"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "peri2organise"
  volumes_from:
    - data
  ports:
    - "5432:5432"
