"""empty message

Revision ID: 4bf85e309c36
Revises: None
Create Date: 2015-10-27 08:18:38.698435

"""

# revision identifiers, used by Alembic.
revision = '4bf85e309c36'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=30), nullable=False),
    sa.Column('telephone_number', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('tutor',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('telephone_number', sa.String(length=11), nullable=False),
    sa.Column('email_address', sa.String(length=30), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(), nullable=False),
    sa.Column('is_account_active', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('speciality', sa.String(length=10), nullable=False),
    sa.Column('staff_role', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('tutor_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('lesson',
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lesson_datetime', sa.DateTime(), nullable=False),
    sa.Column('lesson_duration', sa.Integer(), nullable=False),
    sa.Column('lesson_notes', sa.Text(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('lesson_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=30), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(), nullable=False),
    sa.Column('is_account_active', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('tutor_group', sa.String(length=6), nullable=False),
    sa.Column('musical_instrument_type', sa.String(length=10), nullable=False),
    sa.Column('musical_instrument', sa.String(length=20), nullable=False),
    sa.Column('musical_style', sa.String(length=9), nullable=False),
    sa.Column('musical_grade', sa.Integer(), nullable=False),
    sa.Column('lesson_type', sa.String(length=10), nullable=False),
    sa.Column('lesson_pairing', sa.String(length=40), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.parent_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('instrument',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('instrument_name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('lesson_tutor_association',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.tutor_id'], ),
    sa.PrimaryKeyConstraint('tutor_id', 'lesson_id')
    )
    op.create_table('student_lesson_association',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('attendance_code', sa.String(length=1), nullable=True),
    sa.Column('attendance_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.lesson_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'lesson_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_lesson_association')
    op.drop_table('lesson_tutor_association')
    op.drop_table('instrument')
    op.drop_table('student')
    op.drop_table('lesson')
    op.drop_table('tutor')
    op.drop_table('room')
    op.drop_table('parent')
    ### end Alembic commands ###
