"""empty message

Revision ID: 5746b17000bb
Revises: 455fc643f2ae
Create Date: 2015-10-27 19:05:05.365061

"""

# revision identifiers, used by Alembic.
revision = '5746b17000bb'
down_revision = '455fc643f2ae'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'speciality',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'telephone_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telephone_number',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('user', 'speciality',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    ### end Alembic commands ###
